@startuml
Actor PowerUser

-> EnergyConsumptionUI: selectDevices
EnergyConsumptionUI -> inputHelperUI: getInputDevice
inputHelperUI --> EnergyConsumptionUI: return Device
EnergyConsumptionUI -> EnergyConsumptionController: listContainsDevice(selectedDevices, device)
EnergyConsumptionController -> DeviceList: contains(device)
DeviceList --> EnergyConsumptionUI: return true / false
alt if not yet selected
EnergyConsumptionUI -> EnergyConsumptionController: addDeviceToList(selectedDevices, device)
EnergyConsumptionController -> DeviceList: add(device)
DeviceList -> EnergyConsumptionUI: return true/false
else if already selected
EnergyConsumptionUI -> PowerUser: remove device?
PowerUser -> EnergyConsumptionUI: remove device
EnergyConsumptionUI -> EnergyConsumptionController: removeDeviceFromList(selectedDevices, device)
EnergyConsumptionController -> DeviceList: remove(device)
DeviceList -> EnergyConsumptionUI: return true/false
end
EnergyConsumptionUI -> PowerUser: display feedback message
@enduml