@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
actor PowerUser

-> ":EnergyConsumptionUI": selectTime
activate PowerUser
activate ":EnergyConsumptionUI"
":EnergyConsumptionUI" -> ":InputUtils": getInputTime()
activate ":InputUtils"
":InputUtils" -> PowerUser: request year input
PowerUser -> ":InputUtils": insert year
":InputUtils" -> PowerUser: request month input
PowerUser -> ":InputUtils": insert month
":InputUtils" -> PowerUser: request day input
PowerUser -> ":InputUtils": insert day
":InputUtils" -> PowerUser: request hour input
PowerUser -> ":InputUtils": insert hour
":InputUtils" -> PowerUser: request minute input
PowerUser -> ":InputUtils": insert minute
":InputUtils" -> ":InputUtils": createDate(year, month, day, hour, minute)
":InputUtils" --> ":EnergyConsumptionUI": return date
deactivate PowerUser
deactivate ":EnergyConsumptionUI"
deactivate ":InputUtils"
@enduml