@startuml

actor PowerUser

-> EnergyConsumptionUI: selectRooms
EnergyConsumptionUI -> inputHelperUI: getInputRoom(grid)
inputHelperUI--> EnergyConsumptionUI: return room
EnergyConsumptionUI -> EnergyConsumptionController: listContainsRoom(selectedRooms, room)
EnergyConsumptionController -> RoomList: contains(room)
RoomList --> EnergyConsumptionUI: return true / false
alt if not yet selected
EnergyConsumptionUI -> EnergyConsumptionController: addRoomToList(selectedRooms, room)
EnergyConsumptionController -> RoomList: add(room)
RoomList -> EnergyConsumptionUI: return true/false
EnergyConsumptionUI -> EnergyConsumptionController: addRoomDevicesToList(selectedDevices, room)
EnergyConsumptionController -> Room: addRoomDevicesToList(selectedDevices)
loop addDevice
Room -> DeviceList: addDevice
end
DeviceList --> Room:  return DeviceList;
DeviceList --> EnergyConsumptionUI: return true / false
else if already selected
EnergyConsumptionUI -> PowerUser: remove room?
PowerUser -> EnergyConsumptionUI: removeRoomFromList(selectedRooms, room)
EnergyConsumptionController -> RoomList: remove(room)
RoomList -> EnergyConsumptionUI: return true/false
EnergyConsumptionUI -> EnergyConsumptionController: removeRoomDevicesFromList(selectedDevices, room)
EnergyConsumptionController -> Room: removeRoomDevicesFromList(selectedDevices)
loop removeDevice
Room -> DeviceList: removeDevice
end
DeviceList --> Room: return DeviceList;
DeviceList --> EnergyConsumptionUI: return true / fal se
end
EnergyConsumptionUI -> PowerUser: display feedback message
@enduml