@startuml
actor User

User -> MainUI: Get Current Temperature In A Room
MainUI -> HouseMonitoringUI: Get Current Temperature In A Room
HouseMonitoringUI --> User: Request Room Name or Index from List
User -> MainUI: insert data (Room name) or select Room from List
MainUI -> HouseMonitoringUI: set data (Room name or Index)
HouseMonitoringUI -> HouseMonitoringController: check if name/index is contained in list
HouseMonitoringController -> RoomList: check if name/index is contained in list
RoomList -> Room: match by name or by index
Room -> Room: validate data
Room --> HouseMonitoringUI: set data (Room)
HouseMonitoringUI --> User: Request Sensor Name
User -> MainUI: insert data (Sensor name)
MainUI -> HouseMonitoringUI: set data (Sensor name)
HouseMonitoringUI -> HouseMonitoringController: check if name is contained in list
HouseMonitoringController -> SensorList: check if name is contained in list
SensorList -> Sensor: match by name
Sensor -> Sensor: validate data
Sensor --> HouseMonitoringUI: set data (Sensor)
HouseMonitoringUI -> Room: getCurrentRoomTemperature
Room->Sensor: getSensor
Sensor->ReadingList: getReadingList
ReadingList->Reading: getMostRecentValueOfReading
Reading-->User: Display Current Room Temperature
@enduml