@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

title US011 \n As an Administrator, I want to remove a sensor from a geographical area, so that it will no longer be used.

actor Admin
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
autonumber
Admin -> MainUI:run()
activate MainUI
MainUI -> ":GASettingsUI": runUS011()
activate ":GASettingsUI"
ref over ":GASettingsUI"
Select GeographicAreaDTO
end ref
ref over ":GASettingsUI"
Select SensorDTO
end ref
":GASettingsUI" -> ":GASettingsController": removeSensor( GeographicAreaList, SensorDTO , GeographicAreaDTO )
activate ":GASettingsController"
":GASettingsController" -> ":Mapper": sensorDTOToObject(sensorDTO)
create ":Sensor"
":Mapper" ->> ":Sensor": create
":Sensor" --> ":GASettingsController": return Sensor
loop Geographical Areas in Geographical Areas List till Geographical Area name matches
":GASettingsController" -> GeographicArea: removeSensor (:Sensor)
GeographicArea -> GeographicArea: removeSensor (Sensor)
end

deactivate ":GASettingsController"
":GASettingsUI" --> Admin: Successful feedback message
deactivate ":GASettingsUI"
deactivate MainUI
@enduml