@startuml

title Select SensorDTO

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }

-> GASettingsController: inputSensor( GeographicAreaDTO )
activate GASettingsController
GASettingsController -->> InputHelperUI: sensor = getInputSensorByList(SensorList)
GASettingsController -->> Mapper: Mapper mapper = new Mapper();
activate Mapper
Mapper -> Mapper: sensorToDTO(sensor)
Mapper -> GASettingsController
deactivate Mapper


@enduml