@startuml

title Select GeographicAreaDTO

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }

-> GASettingsController: inputArea( GeographicAreaList )
activate GASettingsController
GASettingsController -->> InputHelperUI: geographicArea = getGeographicAreaByList(geographicAreaList)
GASettingsController -->> Mapper: Mapper mapper = new Mapper();
activate Mapper
Mapper -> Mapper: geographicAreaToDTO(geographicArea)
Mapper -> GASettingsController
deactivate Mapper

@enduml