@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}



title XMLFileReading
-> ReaderController: readReadingsFromXML(geographicAreaList, filePath, logPath)
activate ReaderController

ReaderController -> ReaderController: SensorList sensorList = geographicAreaList.getAreaListSensors();
create "xmlRead :ReaderXMLReadings"
ReaderController -> "xmlRead :ReaderXMLReadings": new ReaderXMLReadings();
activate "xmlRead :ReaderXMLReadings"
ref over "xmlRead :ReaderXMLReadings"
Read readings from
XML file reading
end ref
ReaderController -> "xmlRead :ReaderXMLReadings": Document doc = xmlRead.readFile(filePath);
deactivate "xmlRead :ReaderXMLReadings"

ReaderController -> ReaderController: NodeList list = doc.getElementsByTagName("reading");

loop  Element reading CONTAINED IN list
ReaderController -> ReaderController: parseAndLogXMLReading(sensorList, reading, logger);
ref over ReaderController
Parse and Add Readings To Sensors
end ref

end

<- ReaderController: int added Readings
deactivate "ReaderController"

@enduml