@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}



title XMLReadFile
-> ReaderXML: readFile(String filePath)
activate ReaderXML
alt try
ReaderXML  -> File: File file = new File(filePath)
ReaderXML  -> DocumentBuilderFactory: DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();

ReaderXML -> DocumentBuilder: DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
ReaderXML -> Document: doc = dBuilder.parse(inputFile);

<- ReaderXML: doc

else catch IOException
<- ReaderXML : throw new IllegalArgumentException();
deactivate ReaderXML
end

@enduml