@startuml
actor User
User -> MainUI: Get Average Rainfall on House Area
HouseMonitoringUI --> User: Request Date
User -> HouseMonitoringUI: insert startDate (Date(y-m-d))
MainUI -> HouseMonitoringUI: create data (Date(y-m-d))
HouseMonitoringUI -> HouseMonitoringUI: set data (year1, month1, day1)
User -> HouseMonitoringUI: insert endDate (Date(y-m-d))
MainUI -> HouseMonitoringUI: create data (Date(y-m-d))
HouseMonitoringUI -> HouseMonitoringUI: set data (year2, month2, day2)
HouseMonitoringUI -> HouseMonitoringController: createDate (year1, month1, day1)
HouseMonitoringController --> HouseMonitoringUI: return initialDate
HouseMonitoringUI -> HouseMonitoringController: createDate (year2, month2, day2)
HouseMonitoringController --> HouseMonitoringUI: return endDate
HouseMonitoringUI -> HouseMonitoringController: getAVGDailyRainfallOnGivenPeriod(mHouse, initialDate, endDate)
HouseMonitoringController -> GeographicArea: getAvgReadingsFromSensorTypeInGA ("rain", initialDate, endDate)
GeographicArea -> ReadingList: getAverageReadingsBetweenTwoDays ("rain", initialDate, endDate)
ReadingList --> GeographicArea: return AVGValuesFromDaysWithReadings
GeographicArea --> HouseMonitoringController: return AVGReadingsFromSensorType
HouseMonitoringController -->  HouseMonitoringUI: return AVGReadingsFromSensorType
HouseMonitoringUI -> HouseMonitoringUI: Build result string
HouseMonitoringUI -->User: Display result string
@enduml