@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
title US220 As an Administrator, I want to remove a device from a room, so that it is no longer used. Its activity log is also removed.
autonumber
Administrator -> ":RoomConfigurationUI": runUS222(house)
activate ":RoomConfigurationUI"
ref over ":RoomConfigurationUI"
Select Room
end ref
ref over ":RoomConfigurationUI"
Select Device
end ref
":RoomConfigurationUI" -> ":RoomConfigurationController": removeDevice()
activate ":RoomConfigurationController"
":RoomConfigurationController" -> ":Room": removeDevice(Room, Device)
alt if is Removed
":Room" -> ":Room": removeDevice(Device)
":Room" --> ":RoomConfigurationController": return true
else if else
":Room" -> ":RoomConfigurationController": return false
end
":RoomConfigurationController" --> ":RoomConfigurationUI": return true
deactivate ":RoomConfigurationController"
":RoomConfigurationUI" --> Administrator: Successful feedback message
deactivate ":RoomConfigurationUI"
@enduml