@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
title US060 -  As an Administrator, I want that whenever there is more than one sensor to choose from to get readings,the nearest one should be used.\n A fall-back selection criterion is the one with the latest readings (to the instant/period in analysis).
autonumber
actor Admin
activate Admin
Admin -> ":MainUI": run(house,\n geographicArea)
activate ":MainUI"
":MainUI" -> ":HouseMonitoringUI": runUS600(house,\n geographicArea)
activate ":HouseMonitoringUI"
":HouseMonitoringUI" -> ":HouseMonitoringController": getCurrentTemperatureInTheHouseArea(house,\n geographicArea, sensorType: "temperature")
activate ":HouseMonitoringController"
":HouseMonitoringController"->":House":getSensorWithTheMinimumDistanceToHouse(house,\ngeographicArea, sensorType: "temperature")
activate ":House"
alt if there is more \nthan one sensor closest\n to the house
":House"->":GeographicArea":getSensorList()
activate ":GeographicArea"
":GeographicArea"->":SensorList":getMostRecentlyUsedSensor()
activate ":SensorList"
":SensorList"-->":GeographicArea": return sensor
deactivate ":SensorList"
":GeographicArea"-->":House": return sensor
deactivate ":GeographicArea"
end
":House"-->":HouseMonitoringController": return sensor
deactivate ":House"
":HouseMonitoringController"->":ReadingList": getMostRecentValueOfReading(sensor)
activate ":ReadingList"
":ReadingList"-->":HouseMonitoringController": return double
deactivate ":ReadingList"
":HouseMonitoringController"-->":HouseMonitoringUI": return double
deactivate ":HouseMonitoringController"

":HouseMonitoringUI"->":HouseMonitoringUI": buildResultString()
":HouseMonitoringUI"->":MainUI": displayResultString()
deactivate ":HouseMonitoringUI"
":MainUI"->"Admin": displayResultString()
deactivate ":MainUI"
@enduml