@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

title REF Last Coldest Day in Given Interval
autonumber
activate ":Sensor"
":Sensor"->":ReadingList":getLastColdestDayInGivenInterval(Date, Date)
activate ":ReadingList"
":ReadingList"->":ReadingList":getReadingListBetweenDates(Date, Date)
":ReadingList"->":ReadingList":getListOfMaxValuesForEachDay()
":ReadingList"->":ReadingList":getMinValueInReadingList();
":ReadingList"->":ReadingList": getReadingListOfReadingsWithSpecificValue(minValueInList);
":ReadingList"->":ReadingList": getMostRecentReadingDate();
":ReadingList"-->":ReadingList": return Date
":ReadingList"-->":Sensor": return Date
deactivate ":ReadingList"
deactivate ":Sensor"
@enduml