@startuml
title US630 Class Diagram

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 2
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName verdana

skinparam class {
 	BorderColor indianred
 	BackgroundColor indianred
 	BackgroundColor ivory
    roundcorner 10
    ArrowFontName Verdana
    ArrowColor indianred
    ArrowFontColor darkslategrey
 }

class House
MainUI -- HouseMonitoringUI : >
HouseMonitoringUI -- InputUtils : >
HouseMonitoringUI -- HouseMonitoringController : >
HouseMonitoringController -- House : >
House "1" -- "1" GeographicArea : has >
GeographicArea "1" -- "1" SensorList : has >
SensorList -- Sensor
Sensor "n" -- "1" Location: is in >
Sensor "n" -- "1" TypeSensor: has >
Sensor -- ReadingList

class HouseMonitoringUI {
runUS630(House)
getStartDate()
getEndDate()
updateAndDisplayUS630()
}

class InputUtils{
getInputYearMonthDay()
}

class HouseMonitoringController {
getLastColdestDayInInterval(House, Date, Date)
}

class House{
motherArea;

getClosestSensorOfGivenType(String)
getMinDistanceToSensorOfGivenType(String)
}

class GeographicArea{
SensorList;

getSensorsOfGivenType()
}

class SensorList{
List<Sensor> sensors
ReadingList readingList

getSensorListByType(String)
getSensorsByDistanceToHouse(House, double)
getMostRecentlyUsedSensor()
getMostRecentReadingDate()
}

class Sensor{
TypeSensor;
Local;

getSensorTypeName()
getDistanceToHouse(House)
getLinearDistanceBetweenLocalsInKm(Location)
getLastColdestDayInInterval(Date, Date)
}

class TypeSensor{
name;

getName()
}



class Location{
double latitude;
double longitude;

getLinearDistanceBetweenLocalsInKm(Location)
}

class ReadingList{
List<Reading> readings;

getMostRecentReadingDate()
getReadingListBetweenDates()
getListOfMaxValuesForEachDay()
getMinValueInReadingList()
getReadingListOfReadingsWithSpecificValue(minValueInList)
getMostRecentReading()
getMaxValueOfTheDay()
getFirstSecondOfDay(Date)
getLastSecondOfDay(Date)
isReadingDateBetweenTwoDates(Date, Date, Date)
compareDayMonthAndYearBetweenDates(Date, Date)
getValuesOfSpecificDayReadings(Date)
getAReadingWithSpecificDay(Date)

}

@enduml