@startuml

skinparam titleBorderRoundCorner 25
skinparam titleBorderThickness 3
skinparam titleBorderColor salmon
skinparam titleBackgroundColor lightsalmon-lightpink
skinparam FontName Verdana

title US172 \n I want to know the total nominal power connected to a grid

skinparam actor {
	BorderColor salmon
	}

skinparam sequence {
	LifeLineBackgroundColor salmon
	ParticipantBackgroundColor PeachPuff
}

skinparam roundcorner 20

skinparam component {
  arrowThickness 2
  ArrowFontName Verdana
  ArrowColor salmon
  ArrowFontColor darkslategrey
}

actor André
André -> MainUI: getEnergyGridTotalPower(House)
MainUI -> EnergyConsumptionUI: runEnergyConsumptionUI(house)
activate EnergyConsumptionUI
EnergyConsumptionUI -> EnergyConsumptionUI: run US172(house)
EnergyConsumptionUI -> EnergyConsumptionUI: getInputGrid()
André <-- EnergyConsumptionUI: display inputGrid

EnergyConsumptionUI -> EnergyConsumptionController: getGridTotalPower(grid)
activate EnergyConsumptionController
EnergyGridSettingsController -> EnergyGrid: getGridTotalNominalPower()
activate EnergyGrid
EnergyGrid -> RoomList: getRoomList()
activate RoomList
RoomList --> EnergyGrid: return RoomList
deactivate RoomList
EnergyGrid -> Room: getRoomTotalNominalPower()
activate Room
Room -> DeviceList: getDeviceList()
activate DeviceList
DeviceList --> Room: return DeviceList
deactivate DeviceList
Room -> Device: getDeviceTotalNominalPower()
activate Device
Device --> Room: return deviceTotalNominalPower
deactivate Device
Room --> EnergyGrid: return roomTotalNominalPower
deactivate Room
EnergyGrid --> EnergyConsumptionController: return gridTotalNominalPower
deactivate EnergyGrid
EnergyConsumptionController --> EnergyConsumptionUI: return gridNominalPower
deactivate EnergyConsumptionController
EnergyConsumptionUI --> André: gridTotalNominalPower
deactivate EnergyConsumptionUI

@endumlΩ