@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

title REF Closest Sensor Selection
autonumber

":HouseMonitoringController"->":House":getClosestSensorOfGivenType(String)
activate ":House"
alt if there is more \nthan one sensor closest\n to the house
":House"->":GeographicArea":getSensorList()
activate ":GeographicArea"
":GeographicArea"->":SensorList":getMostRecentlyUsedSensor()
activate ":SensorList"
":SensorList"-->":GeographicArea": return sensor
deactivate ":SensorList"
":GeographicArea"-->":House": return sensor
deactivate ":GeographicArea"
end
":House"-->":HouseMonitoringController": return sensor
deactivate ":House"

@enduml