@startuml
title US631 Class Diagram

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 2
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName verdana

skinparam class {
 	BorderColor indianred
 	BackgroundColor indianred
 	BackgroundColor ivory
    roundcorner 10
    ArrowFontName Verdana
    ArrowColor indianred
    ArrowFontColor darkslategrey
 }

class House
MainUI -- HouseMonitoringUI : >
HouseMonitoringUI -- InputUtils : >
HouseMonitoringUI -- HouseMonitoringController : >
HouseMonitoringController -- House : >
House "1" -- "1" GeographicArea : has >
GeographicArea "1" -- "1" SensorList : has >
SensorList"1" -- "0.n" Sensor : may have >
Sensor "0.n" -- "1" Location: is in >
Sensor "0.n" -- "1" TypeSensor: has >
Sensor "1" -- "1" ReadingList: has >


class HouseMonitoringUI {
runUS631(House)
getStartDate()
getEndDate()
updateAndDisplayUS631()
}

class InputUtils{
getInputYearMonthDay()
}

class HouseMonitoringController {
getFirstHottestDayInPeriod()

}

class House{
motherArea;

getClosestSensorOfGivenType(String)
getMinDistanceToSensorOfGivenType(String)
}

class GeographicArea{
SensorList;

getSensorsOfGivenType()
}

class SensorList{
List<Sensor> sensors
ReadingList readingList

getSensorListByType(String)
getSensorsByDistanceToHouse(House, double)
getMostRecentlyUsedSensor()
getMostRecentReadingDate()
}

class Sensor{
TypeSensor;
Local;

getSensorTypeName()
getDistanceToHouse(House)
getLinearDistanceBetweenLocalsInKm(Location)
getFirstHottestDayInGivenPeriod(Date, Date)
}

class TypeSensor{
name;

getName()
}



class Location{
double latitude;
double longitude;

getLinearDistanceBetweenLocalsInKm(Location)
}

class ReadingList{
List<Reading> readings;

getMostRecentReadingDate()
getMostRecentReading()
getFirstHottestDayInGivenPeriod(Date, Date)
getDaysWithReadingsBetweenDates(Date, Date)
getReadingListBetweenDates(Date, Date)
isReadingDateBetweenTwoDates(Date, Date, Date)
getAmplitudeValueFromDate(Date)
getValuesOfSpecificDayReadings(Date)
getFirstSecondOfDay(Date)
getLastSecondOfDay(Date)
compareDayMonthAndYearBetweenDates(Date, Date)
getMaxValue(List<Date>)
getFirstDayForGivenTemperature(Double, List<Date>)

}

@enduml