@startuml
title US010 \n As an Administrator, I want to deactivate a sensor in a geographical area, \n so that it will no longer be used. It can be reactivated later.
actor Admin
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
autonumber
Admin -> ":GASettingsUI": runUS10()
activate ":GASettingsUI"
ref over ":GASettingsUI"
Select GeographicAreaDTO
end ref
ref over ":GASettingsUI"
Select SensorDTO
end ref
":GASettingsUI" -> ":GASettingsController": deactivateSensor(geographicAreaList,sensorDTO, geographicAreaDTO)
activate ":GASettingsController"
":GASettingsController" -> ":Mapper": sensorDTOToObject(sensorDTO)

create ":Sensor"

":Mapper" ->> ":Sensor": create
activate ":Sensor"
":Sensor" --> ":GASettingsController": return Sensor
deactivate ":Sensor"
alt if isActive()
":GASettingsController" -> ":Sensor": deactivate()
":Sensor" -> ":GeographicArea": add(sensor)
":Sensor" --> ":GASettingsController": return true
else if else
":Sensor" -> ":GASettingsController": return false
end
":GASettingsController" --> ":GASettingsUI": return true
deactivate ":GASettingsController"
":GASettingsUI" --> Admin: Successful feedback message
deactivate ":GASettingsUI"
@enduml