@startuml
title Domain Model

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 2
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName verdana

skinparam class {
 	BorderColor indianred
 	BackgroundColor indianred
 	BackgroundColor ivory
    roundcorner 10
    ArrowFontName Verdana
    ArrowColor indianred
    ArrowFontColor darkslategrey
 }

class House

House "1" -- "1" GeographicArea : has >
House "1" -- "0,n" Room : may have 4 >
House "1" -- "0,n" EnergyGrid: may have >
EnergyGrid "1" -- "1" PowerSource: has >
EnergyGrid "1" -- "0,n" Room: may have >
Room "1" -- "0,n" Device : may have >
House "1" -- "1" Location :  is in >
Location "1" -- "1" GeographicArea: is in >
GeographicArea "0,n" -- "1" AreaType: is of >
GeographicArea "1" -- "0,n" Sensor: may have>
Sensor "n" -- "1" SensorType: is of >
Device "1" .. "1" WaterHeater
Device "1" .. "1" Fridge
Device "1" .. "1" etc


class Room {
name;
floor;
width;
length;
height;
}

class House {
id;
address;
deviceTypeList;
}

class Location {
latitude;
longitude;
altitude;
}

class EnergyGrid{
name;
nominal power;
}

class PowerSource{
name;
max output;
max storage;
}

Interface Device{
name;
active;
}

class GeographicArea{
id;
description;
}

class Sensor{
name;
starting date;
}

class AreaType{
name;
}

class SensorType{
 name;
 units;
 }

 class WaterHeater{
 nominal power;
 volume;
 hot water temperature;
 efficiency coefficient;
 }

 class Fridge{
 nominal power;
 freezer capacity;
 refrigerator capacity;
 }


@enduml