@startuml
title US222 As a Power User, I want to deactivate a device, so that it is no longer used.\nNevertheless, it should be possible to access its configuration and activity log.
actor PowerUser
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
autonumber
PowerUser -> ":RoomConfigurationUI": runUS222(house)
activate ":RoomConfigurationUI"
ref over ":RoomConfigurationUI"
Select Room
end ref
ref over ":RoomConfigurationUI"
Select Device
end ref
":RoomConfigurationUI" -> ":RoomConfigurationController": deactivateDevice(device)
activate ":RoomConfigurationController"
":RoomConfigurationController" -> ":Device": deactivate()
alt if isActive()
":Device" -> ":Device": setmActiveFalse()
":Device" --> ":RoomConfigurationController": return true
else if else
":Device" -> ":RoomConfigurationController": return false
end
":RoomConfigurationController" --> ":RoomConfigurationUI": return true
deactivate ":RoomConfigurationController"
":RoomConfigurationUI" --> PowerUser: Successful feedback message
deactivate ":RoomConfigurationUI"
@enduml