@startuml
title US721 As a Power User [or Administrator], I want to know the total metered energy consumption of a room in a given time interval.
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
actor PowerUser
PowerUser -> EnergyConsumptionUI: runUS721
ref over EnergyConsumptionUI
selectRoom
end ref
activate EnergyConsumptionUI
ref over EnergyConsumptionUI
getInputStartDate
end ref
ref over EnergyConsumptionUI
getInputEndDate
end ref
EnergyConsumptionUI -> EnergyConsumptionController: getRoomConsumptionInInterval \n(startDate, endDate, room)
activate EnergyConsumptionController
EnergyConsumptionController -> Room: getConsumptionInInterval \n(startDate, endDate)
activate Room
Room -> DeviceList: getConsumptionInInterval \n(startDate, endDate)
activate DeviceList
loop get consumption for each device in interval
DeviceList -> Device: getConsumptionInInterval \n(startDate, endDate)
activate Device
Device --> DeviceList: return double
deactivate Device
end
DeviceList --> Room: return sum
deactivate DeviceList
Room --> EnergyConsumptionController: return sum
deactivate Room
EnergyConsumptionController --> EnergyConsumptionUI: return consumptionInInterval
deactivate EnergyConsumptionController
EnergyConsumptionUI -> PowerUser: display total consumption in given interval
deactivate EnergyConsumptionUI
@enduml