@startuml
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
title US722 As a Power User [or Administrator], I want to know the total metered energy consumption of a grid in agiven time interval.
actor PowerUser
PowerUser -> EnergyConsumptionUI: runUS722
activate EnergyConsumptionUI
ref over EnergyConsumptionUI
selectGrid
end ref
ref over EnergyConsumptionUI
getInputStartDate
end ref
ref over EnergyConsumptionUI
getInputEndDate
end ref
EnergyConsumptionUI -> EnergyConsumptionController: getGridConsumptionInInterval \n(grid, startDate, endDate)
activate EnergyConsumptionController
EnergyConsumptionController -> Grid: getConsumptionInInterval \n(startDate, endDate)
activate Grid
Grid -> RoomList: getConsumptionInInterval \n(startDate, endDate)
activate RoomList
loop get consumption for each room
RoomList -> Room: getConsumptionInInterval \n(startDate, endDate)
activate Room
Room --> RoomList: return double
deactivate Room
end
RoomList --> Grid: return sum
deactivate RoomList
Grid --> EnergyConsumptionUI: return consumptionInInterval
deactivate Grid
deactivate EnergyConsumptionController
EnergyConsumptionUI -> PowerUser: display total consumption in given interval
deactivate EnergyConsumptionUI
@enduml