@startuml
autonumber

actor Admin
Admin -> MainUI: getRoomNominalPower
MainUI -> RoomConfigurationUI: runUS230
RoomConfigurationUI -> RoomConfigurationUI: getInputRoom()
RoomConfigurationUI -> Admin: displayRoomList
Admin -> RoomConfigurationUI: index of room
RoomConfigurationUI -> RoomConfigurationController: getRoomNominalPower(room)
RoomConfigurationController -> Room: getNominalPower()
Room -> DeviceList: getDeviceList()
DeviceList --> Room: return DeviceList
Room -> Device: device.getNominalPower()
Device --> Room: return deviceNominalPower
Room --> RoomConfigurationController: return roomNominalPower
RoomConfigurationController --> RoomConfigurationUI: return roomNominalPower
RoomConfigurationUI -> Admin: display room's nominal power

@endumlΩ