@startuml
actor User
autonumber
User -> MainUI: Get Max Temperature In A Room On A Given Day
MainUI -> HouseMonitoringUI: runUS610()
HouseMonitoringUI --> User: displayRoomList()
User -> HouseMonitoringUI: Select Room from Room list
ref over HouseMonitoringUI
Select Room
end
HouseMonitoringUI --> User: Request Date

User -> HouseMonitoringUI: insert date (Date(y-m-d))
ref over HouseMonitoringUI
Select Day
end
HouseMonitoringUI -> Room: getMaxTemperatureInARoomOnAGivenDay(Date)
Room->SensorList: getSensorList()
SensorList->ReadingList: getReadingList()
ReadingList->Reading:getMaximumOfGivenDayValueReadings(Date)
Reading-->User: Display Maximum Temperature In Date
@enduml