@startuml
title US015v2 \n REF XML file.
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}


title US80 \n As an administrator, I want the data related to geographical areas, including sensors and their readings,\n to be persisted in a relational database, so that this data is available whenever the application is run.

autonumber

ReaderController -> SensorService: addReadingToMatchingSensor \n (SensorList, String, double, Date)
activate ReaderController
activate SensorService
SensorService -> SensorList: addReadingToMatchingSensor(String, double, Date)
activate SensorList
SensorList --> SensorService: return true
deactivate SensorList
SensorService -> SensorRepository: findById(sensorID).get()
activate SensorRepository
SensorRepository --> SensorService: return :Sensor
deactivate SensorRepository
create "r:Reading"
SensorService ->> "r:Reading": create
activate "r:Reading"
"r:Reading" --> SensorService: return r
deactivate "r:Reading"
SensorService -> ":Sensor": getReadingList()
activate ":Sensor"
":Sensor" --> SensorService: return :ReadingList
deactivate ":Sensor"
SensorService -> "r:Reading": setReadingList(:ReadingList)
SensorService -> ReadingRepository: save(r)
SensorService --> ReaderController: return true
deactivate SensorService
deactivate ReaderController

@enduml