@startuml
title US015v2 \n REF XML file.
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}


title US80 \n As an administrator, I want the data related to geographical areas, including sensors and their readings,\n to be persisted in a relational database, so that this data is available whenever the application is run.

autonumber

ReaderController -> GeographicAreaList: addGeographicArea(:GeographicArea)
activate ReaderController
activate GeographicAreaList
GeographicAreaList -> GeographicAreaList: contains(:GeographicArea)
alt false
GeographicAreaList -> GeographicAreaList: add(:GeographicArea)
GeographicAreaList -> GeographicAreaRepository: save(:GeographicArea)
GeographicAreaList --> ReaderController: return true
else true
GeographicAreaList --> ReaderController: return false
deactivate GeographicAreaList
deactivate ReaderController
end alt
@enduml