@startuml
actor Admin

Admin->MainUI: I Wish to Create a new Type of Geographic Area
MainUI->HouseConfigurationUI: Create a new Type of Geographic Area
HouseConfigurationUI --> Admin: Request the Name of the new Geographic Area Type
Admin -> MainUI: insert data (type Area Name)
MainUI -> HouseConfigurationUI: set data (type Area Name)
HouseConfigurationUI -> HouseConfigurationController: createAndAddTypeAreaToList
HouseConfigurationController->TypeAreaList: newTypeOfGeographicArea(type Area Name)
TypeAreaList->TypeAreaList:addTypeArea
TypeAreaList-->Admin: Display Success
@enduml