@startuml



actor PowerUser

-> ":HouseMonitoringUI": selectTime
activate PowerUser
activate ":HouseMonitoringUI"
":HouseMonitoringUI" -> ":InputUtils": getInputTime()
activate ":InputUtils"
":InputUtils" --> PowerUser: request year input
PowerUser -> ":InputUtils": insert year
":InputUtils" --> PowerUser: request month input
PowerUser -> ":InputUtils": insert month
":InputUtils" -> PowerUser: request day input
PowerUser -> ":InputUtils": insert day
":InputUtils" --> PowerUser: request hour input
PowerUser -> ":InputUtils": insert hour
":InputUtils" -> PowerUser: request minute input
PowerUser -> ":InputUtils": insert minute
":InputUtils" -> ":InputUtils": createDate(year, month, day)
":InputUtils" --> ":HouseMonitoringUI": return date
deactivate PowerUser
deactivate ":HouseMonitoringUI"
deactivate ":InputUtils"
@enduml