@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
actor Administrator

-> ":RoomConfigurationUI": selectRoom
activate ":RoomConfigurationUI"
":RoomConfigurationUI" -> ":InputUtils": getInputRoom(:House)
activate ":InputUtils"
":InputUtils" -> ":House": getRoomList()
activate ":House"
":House" -> ":RoomList": getRoomList()
activate ":RoomList"
":RoomList" --> ":InputUtils": return :RoomList
deactivate ":RoomList"
deactivate ":House"
":InputUtils" -> ":InputUtils": buildRoomListString()
":InputUtils" -> Administrator: display list of available rooms
Administrator -> ":InputUtils": select room by index
":InputUtils" -> ":House": getRoomByIndex()
activate ":House"
":House" -> ":RoomList": getRoomByIndex()
activate ":RoomList"
":RoomList" --> ":RoomConfigurationUI" : return :Room
deactivate ":RoomList"
deactivate ":House"
deactivate ":RoomConfigurationUI"
deactivate ":InputUtils"
@enduml