@startuml
actor Admin
title US215 \n As an Administrator, I want to edit the configuration of an existing device, so that I can reconfigure it. \n Select a Device from the selected Room's Device list.
autonumber
RoomConfigurationUI --> Admin:displayDeviceListFromRoom()
Admin -> RoomConfigurationUI: Select Device from Device list
activate RoomConfigurationUI
RoomConfigurationUI -> RoomConfigurationController: getDeviceFromList()
activate RoomConfigurationController
RoomConfigurationController -> DeviceList:  getDeviceFromList()
activate DeviceList
DeviceList->Device: getDeviceFromList()
activate Device
Device -> Device: validate Device
Device --> Admin: displayDevice()
deactivate Device
deactivate DeviceList
deactivate RoomConfigurationController
deactivate RoomConfigurationUI
@enduml