@startuml
actor Admin
title US215 \n As an Administrator, I want to edit the configuration of an existing device, so that I can reconfigure it. \n Select a Room from the House's RoomList
autonumber
RoomConfigurationUI --> Admin: displayRoomList()
Admin -> RoomConfigurationUI: Select Room from Room list
activate RoomConfigurationUI
RoomConfigurationUI -> RoomConfigurationController: getRoomFromList()
activate RoomConfigurationController
RoomConfigurationController -> RoomList: getRoomFromList()
activate RoomList
RoomList->Room: getRoomFromList()
activate Room
Room -> Room: validate Room
Room --> Admin: displayRoom()

deactivate Room
deactivate RoomList
deactivate RoomConfigurationController
deactivate RoomConfigurationUI
@enduml