@startuml
actor User
User -> MainUI: Add a new room to a house.
MainUI -> HouseConfigurationUI: Add a new room to a house.
HouseConfigurationUI --> User: request house specs (room name, house floor, dimensions)
User -> MainUI: insert specs (room name, house floor, dimensions)
MainUI -> HouseConfigurationUI: set data
HouseConfigurationUI -> HouseConfigurationController: create Room
HouseConfigurationController -> Room: create Room
Room -> Room: validate data
Room --> User: display house
HouseConfigurationUI --> User: Request Geographic Area Name
User -> MainUI: insert data (Geographic Area name)
MainUI -> HouseConfigurationUI: set data (Geographic Area name)
HouseConfigurationUI ->HouseConfigurationController: check if name is contained in list
HouseConfigurationController -> GeographicAreaList: check if name is contained in list
GeographicAreaList -> GeographicArea: match by name
GeographicArea -> GeographicArea: validate data
GeographicArea --> HouseConfigurationUI: set data (Geographic Area)
HouseConfigurationUI --> User: Request House Name
User -> MainUI: insert data (House name)
MainUI -> HouseConfigurationUI: set data (House name)
HouseConfigurationUI -> HouseConfigurationController: check if name is contained in list
HouseConfigurationController -> HouseList: check if name is contained in list
HouseList -> House: match by name
House -> House: validate data
House --> HouseConfigurationUI: set data (House)
HouseConfigurationUI -> House: check if Room is in House
House -> House: add Room to House
House --> User: display New Room in House

@enduml