@startuml

actor PowerUser
PowerUser -> EnergyConsumptionUI: runUS730
alt EnergyGrid
activate EnergyConsumptionUI
EnergyConsumptionUI -> inputHelperUI
ref over inputHelperUI
selectGrid
end ref
activate inputHelperUI
ref over inputHelperUI
selectInitialTime
end ref
ref over inputHelperUI
selectFinalTime
end ref
EnergyConsumptionUI -> EnergyConsumptionController: getGridLogsInInterval(grid)
deactivate inputHelperUI
activate EnergyConsumptionController
EnergyConsumptionController -> EnergyGrid: getLogsInInterval
activate EnergyGrid
ref over EnergyGrid
getLogsInInterval
end ref
EnergyGrid --> EnergyConsumptionUI: return LogList
deactivate EnergyGrid
deactivate EnergyConsumptionController
else Room
EnergyConsumptionUI -> inputHelperUI
activate inputHelperUI
ref over inputHelperUI
select Room
end ref
ref over inputHelperUI
selectInitialTime
end ref
ref over inputHelperUI
selectFinalTime
end ref
EnergyConsumptionUI -> EnergyConsumptionController: getRoomLogsInInterval(room)
deactivate inputHelperUI
activate EnergyConsumptionController
EnergyConsumptionController -> Room: getLogsInInterval;
activate Room
ref over Room
getLogsInInterval
end ref
Room --> EnergyConsumptionUI: return LogList;
deactivate EnergyConsumptionController
deactivate Room
else Device
EnergyConsumptionUI -> inputHelperUI
activate inputHelperUI
ref over inputHelperUI
selectRoom
end ref
ref over inputHelperUI
selectDevice
end ref
ref over inputHelperUI
selectInitialTime
end ref
ref over inputHelperUI
selectFinalTime
end ref
EnergyConsumptionUI -> EnergyConsumptionController: getDeviceLogsInInterval(device)
deactivate inputHelperUI
activate EnergyConsumptionController
EnergyConsumptionController -> Device: getLogsInInterval
activate Device
ref over Device
getLogsInInterval
end ref
Device --> EnergyConsumptionUI: return LogList
deactivate Device
deactivate EnergyConsumptionController
end
EnergyConsumptionUI -> EnergyConsumptionController: buildString(LogList)
activate EnergyConsumptionController
EnergyConsumptionController -> LogList: toString()
activate LogList
LogList --> EnergyConsumptionUI: return String
deactivate LogList
deactivate EnergyConsumptionController
EnergyConsumptionUI -> PowerUser: display logs as list with date and value
deactivate EnergyConsumptionUI
@enduml