@startuml
title US215 \n As an Administrator, I want to edit the configuration of an existing device, \n so that I can reconfigure it.

autonumber
actor Admin
Admin -> MainUI: I want to edit the configuration of an existing device \n run()
MainUI -> RoomConfigurationUI: runUS215()
activate RoomConfigurationUI

RoomConfigurationUI --> Admin: displayRoomList()
Admin -> RoomConfigurationUI: Select Room from Room list
ref over RoomConfigurationUI
Select Room
end
RoomConfigurationUI --> Admin:displayDeviceListFromRoom()
Admin -> RoomConfigurationUI: Select Device from Device list
ref over RoomConfigurationUI
Select Device
end
RoomConfigurationUI --> Admin: getInputDeviceCharacteristicsUS215()
Admin-> RoomConfigurationUI: Insert Device settings to configure according to \n Device Type (room, name, nominal Power)
RoomConfigurationUI -> RoomConfigurationController: updateDeviceUS215(room, \n name, nominal Power)
activate RoomConfigurationController
RoomConfigurationController -> "<<Device>>": setDeviceName(), setDeviceNominalPower(),\n removeDeviceFromRoom(),\n addDeviceFromRoom()
activate "<<Device>>"
"<<Device>>" -> "<<Device>>": validate settings
"<<Device>>" -->RoomConfigurationUI: return device
RoomConfigurationUI->"<<Device>>":getAttributeNames()
loop setAttributeValue()
"<<Device>>" -> "<<DeviceSpecs>>": setAttributeValue()
activate "<<DeviceSpecs>>"
end
"<<DeviceSpecs>>"-->"<<Device>>":return specs
deactivate "<<DeviceSpecs>>"
"<<Device>>"-->RoomConfigurationUI:return specs
RoomConfigurationUI->RoomConfigurationController: isProgrammable(device)
RoomConfigurationController->"<<Device>>": isProgrammable(device)

ref over "<<Device>>"
Programmable
end
"<<Device>>"--> Admin: displayDeviceUS215()
deactivate RoomConfigurationUI
deactivate RoomConfigurationController
deactivate "<<Device>>"


@enduml