@startuml
actor Admin
alt if the Device is Programmable
    RoomConfigurationUI --> Admin:displayProgramListFromDevice()
    Admin -> RoomConfigurationUI: Select Program from Program list
    activate RoomConfigurationUI
    RoomConfigurationUI -> RoomConfigurationController: getProgramFromList()
    activate RoomConfigurationController
    RoomConfigurationController -> ":ProgramList": getProgramFromList()
    activate ":ProgramList"
    ":ProgramList"->":Program": getProgramFromList()
    activate ":Program"
    ":Program" -> ":Program": validate Program
    ":Program" --> Admin: displayProgram()
        deactivate ":Program"
    deactivate ":ProgramList"
    deactivate RoomConfigurationController
    deactivate RoomConfigurationUI
    loop setAttributeValueProgram()
    RoomConfigurationUI-->Admin: displayAttributeName()
    Admin->RoomConfigurationUI: insert attribute value
    activate RoomConfigurationUI
    RoomConfigurationUI->RoomConfigurationController:setAttributeValue()
    activate "RoomConfigurationController"
        RoomConfigurationController->":Program":setAttributeValue()
        activate ":Program"
        ":Program"->":Program":validate value

end

@enduml