@startuml
actor Admin
Admin -> MainUI: I want to get a list of all devices in a room
MainUI -> RoomConfigurationUI: run(House)
RoomConfigurationUI --> Admin: displayRoomList()
Admin ->RoomConfigurationUI: insert room from list
RoomConfigurationUI->RoomConfigurationController: checkIfRoomIsContainedInList(index,house)
RoomConfigurationController->RoomList:checkIfRoomIsContainedInList(index,house)
RoomList->RoomList:validate data
RoomList-->RoomConfigurationController:return Room
RoomConfigurationController-->RoomConfigurationUI: setRoom
RoomConfigurationUI->RoomConfigurationController: getDeviceListFromRoom
RoomConfigurationController->Room: printDeviceList()
Room-->RoomConfigurationController:printDeviceList()
RoomConfigurationController-->RoomConfigurationUI:printDeviceList()
RoomConfigurationUI-->Admin:displayDeviceList()
@enduml