

@startuml
title US051 As an Administrator, I want to define the metering period for grids (in minutes) using a configuration file.

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }

actor user
activate MainUI
user -> MainUI: runMainUI()
activate FileInputUtils
MainUI -> FileInputUtils: fileUtils = new FileInputUtils()

alt try
MainUI -> FileInputUtils: validGridMeteringPeriod()

ref over FileInputUtils
grid metering period
validation
end ref

alt valid configuration value
FileInputUtils --> MainUI: true
MainUI -> FileInputUtils: int gridMeteringPeriod = this.mGridMeteringPeriod()

else invalid configuration value
FileInputUtils --> MainUI: false
MainUI -> user: Error message
end

else catch IOException
MainUI -> user: Error message
else catch NumberFormatException
MainUI -> user: Error message

end
@enduml
