
@startuml
title US051 As an Administrator, I want to define the metering period for grids (in minutes) using a configuration file.
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
activate FileInputUtils
-> FileInputUtils: readGridMeteringPeriod()
activate Properties
FileInputUtils -> Properties: prop = new Properties()

alt try
activate FileInputStream
FileInputUtils -> FileInputStream: input = new FileInputStream("resources/meteringPeriods.properties")
FileInputUtils -> Properties: load(input)
FileInputUtils -> Properties: gridMetering = prop.getProperty("GridMeteringPeriod")

else catch
FileInputUtils -> FileInputUtils: IOException

end
activate Integer
alt try
FileInputUtils -> Integer: parseInt(gridMeteringPeriod)
Integer --> FileInputUtils: return gridMeteringPeriod
<-- FileInputUtils: return gridMeteringPeriod


else catch
FileInputUtils -> FileInputUtils: NumberFormatException

end

@enduml
