@startuml

title US03 \n Create a Geographic Area \n Success Case

autonumber

actor Admin

Admin -> MainUI: start program
MainUI --> Admin: Show Menu
Admin -> MainUI: Select Option GeographicAreaSettings
":GeographicAreaSettingsUI" --> Admin: Show Menu
Admin ->  ":GeographicAreaSettingsUI": Select Option Create Geographic Area
Ref over  ":GeographicAreaSettingsUI"
get Geographic Area Types: US02
end ref
":GeographicAreaSettingsUI" --> Admin: Show Type of Geographic Areas
 Admin ->  ":GeographicAreaSettingsUI": Select geographic area type
Ref over ":GeographicAreaSettingsUI"
receiving data for the new geographic area
end ref

":GeographicAreaSettingsUI" -> ":GeographicAreaController":controller.addGeoAreaToList \n(GeographicAreaList, String, TypeArea, \n Local, double, double)
":GeographicAreaController" -> ":GeographicAreaList": checkIfGANotExists(String, TypeArea, Local)
":GeographicAreaList" --> ":GeographicAreaController": return true
":GeographicAreaController" ->":GeographicAreaList": createGA(String, TypeArea, Local, double, double)
":GeographicAreaList" --> ":GeographicAreaController": return GeographicArea
":GeographicAreaController" ->":GeographicAreaList": addGeographicArea(GeographicArea)
":GeographicAreaList" --> ":GeographicAreaController": return true
":GeographicAreaController" -->":GeographicAreaSettingsUI": return true
":GeographicAreaSettingsUI" -> ":GeographicAreaSettingsUI": generateResultUS03(boolean )
":GeographicAreaSettingsUI" --> Admin: show result string

@enduml