@startuml

title US03 \n Create a Geographic Area \n Receive and set data for the new geographic area

autonumber

actor Admin

":GeographicAreaSettingsUI" --> Admin: Request name for geographic area
Admin -> ":GeographicAreaSettingsUI": geographic area name
":GeographicAreaSettingsUI" --> Admin: Request latitude for geographic area
Admin -> ":GeographicAreaSettingsUI": geographic area latitude
":GeographicAreaSettingsUI" --> Admin: Request longitude for geographic area
Admin -> ":GeographicAreaSettingsUI": geographic area longitude
":GeographicAreaSettingsUI" --> Admin: Request altitude for geographic area
Admin -> ":GeographicAreaSettingsUI": geographic area altitude
":GeographicAreaSettingsUI" --> Admin: Request length for geographic area
Admin -> ":GeographicAreaSettingsUI": geographic area length
":GeographicAreaSettingsUI" --> Admin: Request width for geographic area
Admin -> ":GeographicAreaSettingsUI": geographic area width
":GeographicAreaSettingsUI" --> Admin: Request width for geographic area
Admin -> ":GeographicAreaSettingsUI": geographic area width
Admin -> ":GeographicAreaSettingsUI": geographic area width
":GeographicAreaSettingsUI" --> Admin: Ask user if he would like to insert a \n geographic area description
Admin -> ":GeographicAreaSettingsUI": answer "yes"
":GeographicAreaSettingsUI" --> Admin: Request geographic area description
Admin -> ":GeographicAreaSettingsUI": geographic area description

@enduml