@startuml
autonumber
actor Admin
Admin -> MainUI: Get List Of\nSensors in a Room
MainUI -> RoomConfigurationUI: run(house)
RoomConfigurationUI -> InputUtils: getHouseRoomByList(house)
InputUtils -> House: getRoomList()
House -> House: isEmpty()
House --> InputUtils: return
InputUtils -> InputUtils: printRoomList()
InputUtils --> Admin: Display RoomList
Admin --> InputUtils: Select Room
InputUtils -> RoomConfigurationUI: displaySensorListUS250()
RoomConfigurationUI -> Room : getmRoomSensorList()
Room -> Room: isEmpty()
Room --> RoomConfigurationUI: return
RoomConfigurationUI -> RoomConfigurationUI: printSensorList()
RoomConfigurationUI --> Admin: Display SensorList
@enduml