@startuml
actor Admin
alt if the Device is a WaterHeater
    RoomConfigurationUI -> Admin: getHotWaterTemp(double)
    Admin --> RoomConfigurationUI: return hotWaterTemp(double)
    RoomConfigurationUI ->RoomConfigurationUI: set holdWaterTemp(double)
    RoomConfigurationUI -> Admin: getVolumeOfWaterToHeat(double)
    Admin --> RoomConfigurationUI: return VolumeOfWaterToHeat(double)
    RoomConfigurationUI -> RoomConfigurationUI: set VolumeOfWaterToHeat(double)
    RoomConfigurationUI -> Admin: getPerformanceRation(double)
    Admin --> RoomConfigurationUI: return PerformanceRatio(double)
    RoomConfigurationUI -> RoomConfigurationUI: set PerformanceRatio(double)
    RoomConfigurationUI -> RoomConfigurationController: configureOneHeater(Device, double, double, double)
    RoomConfigurationController -> Device: setAttributeValue(String, double)
end
@enduml