@startuml
actor Admin
alt if the Device is a Fridge

    RoomConfigurationUI -> Admin: getFreezerCapacity(double)
    Admin --> RoomConfigurationUI: return freezerCapacity(double)
    RoomConfigurationUI ->RoomConfigurationUI: set getFreezerCapacity(double)
    RoomConfigurationUI -> Admin: getRefrigeratorCapacity(double)
    Admin --> RoomConfigurationUI: return refrigeratorCapacity(double)
    RoomConfigurationUI -> RoomConfigurationUI: set refrigeratorCapacity(double)
    RoomConfigurationUI -> Admin: getEnergyConsumption(double)
    Admin --> RoomConfigurationUI: return EnergyConsumption(double)
    RoomConfigurationUI -> RoomConfigurationUI: set EnergyConsumption(double)
    RoomConfigurationUI -> RoomConfigurationController: configureOneFridge(Device, double, double, double)
    RoomConfigurationController -> Device: setAttributeValue(String, double)
end
@enduml