@startuml
actor Admin
alt if the Device is a Lamp
    RoomConfigurationUI -> Admin: getLuminousFlux(double)
    Admin --> RoomConfigurationUI: return luminousFlux(double)
    RoomConfigurationUI ->RoomConfigurationUI: set luminousFlux(double)
        RoomConfigurationUI -> RoomConfigurationController: configureOneLamp(Device, double, double, double)
    RoomConfigurationController -> Device: setAttributeValue(String, double)
end
@enduml