@startuml
actor Admin
alt if the Device is a DishWasher \n or a WashingMachine
    RoomConfigurationUI -> Admin: getCapacity(double)
    Admin --> RoomConfigurationUI: return capacity(double)
    RoomConfigurationUI ->RoomConfigurationUI: set capacity(double)
    RoomConfigurationUI -> Admin: displayProgramList()
    Admin --> RoomConfigurationUI: Select Program From List Of Programs
    RoomConfigurationUI -> RoomConfigurationController: getProgramFromList()
    RoomConfigurationController->Device:getProgramFromList()
    Device--> Admin:displayProgram()
    RoomConfigurationUI -> Admin: getProgramName(String) \n getProgramDuration(double) \n getProgramEnergyConsumption()
    Admin --> RoomConfigurationUI: return programName(String) \n programDuration(double) \n programEnergyConsumption
    RoomConfigurationUI->RoomConfigurationUI: set attributes
    RoomConfigurationUI -> RoomConfigurationUI: addReconfiguredProgramToList
    RoomConfigurationUI -> RoomConfigurationController: configureDishWasher\n(Device, double, double, programList)
    RoomConfigurationController -> Device: setAttributeValue(String, double)
end
@enduml