@startuml
actor Admin
participant "d1: Device"
Admin -> MainUI: Add Device to a Room from available type
MainUI -> RoomConfigurationUI: Add Device to a Room from available Type
RoomConfigurationUI --> Admin: Display available DeviceTypes
Admin -> MainUI: Select DeviceType from DeviceType list
MainUI -> RoomConfigurationController: Match Device from enum
RoomConfigurationController -> DeviceType: Check if DeviceType is contained
DeviceType -> DeviceType: validate DeviceType
RoomConfigurationUI --> Admin: Display Device settings to configure according to the device type selected
Admin-> RoomConfigurationUI: Insert Device settings to configure
RoomConfigurationUI -> RoomConfigurationController: create new Device
RoomConfigurationController -> Room: add Device to DeviceList in Room
Room -> Room: validate Device
Room--> Admin: display Device added to Device List
@endumlΩ