@startuml

title US752 \n  I want to estimate the total energy used in heating water in a given day \n \n Loop to receive data from user for all water heaters on the house.


autonumber


actor User

loop all house water heaters
    EnergyConsumptionUI --> User: request cold water temperature
        activate EnergyConsumptionUI
    User --> EnergyConsumptionUI: cold water temperature
    EnergyConsumptionUI --> User: request volume of water to heat
    User --> EnergyConsumptionUI: volume of water to heat
    EnergyConsumptionUI -> EnergyConsumptionController: configureHeater(Device, double, double)
        deactivate EnergyConsumptionUI
    EnergyConsumptionController -> Device: setAttributeValue(String, double)
    EnergyConsumptionController -> Device: setAttributeValue(String, double)
end
@enduml