@startuml

title US752 \n  I want to estimate the total energy used in heating water in a given day

autonumber


actor User
activate MainUI
User -> MainUI: request daily energy consumption\n on heating water

MainUI -> EnergyConsumptionUI:  energyConsumptionUI.run(house)

activate EnergyConsumptionUI
EnergyConsumptionUI -> EnergyConsumptionUI: run US752(house)

EnergyConsumptionUI -> EnergyConsumptionController: getWHDeviceList(house)
activate EnergyConsumptionController
EnergyConsumptionController -> House: getDevicesOfGivenType(deviceType)
activate House
House --> EnergyConsumptionController: return WHList
deactivate House
EnergyConsumptionController --> EnergyConsumptionUI: return WHList
deactivate EnergyConsumptionController

ref over EnergyConsumptionUI
Loop to receive data from user for all WH on the house
end


EnergyConsumptionUI -> EnergyConsumptionController: getDailyWHConsumption(house)
activate EnergyConsumptionController
EnergyConsumptionController -> House: getDailyConsumptionByDeviceType(DeviceType)
activate House
House -> Room: getDailyConsumptionByDeviceType(DeviceType)
activate Room
Room -> Device: getDailyConsumption()
activate Device
Device --> Room: return dailyConsumption
deactivate Device
Room --> House: return dailyConsumption
deactivate Room
House --> EnergyConsumptionController: return dailyConsumption
deactivate House
EnergyConsumptionController --> EnergyConsumptionUI: return dailyConsumptionOnWH
deactivate EnergyConsumptionController
EnergyConsumptionUI -> EnergyConsumptionUI: Build result string
EnergyConsumptionUI -> User: Display result string
deactivate EnergyConsumptionUI
deactivate MainUI
@enduml