@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
title US050 \n  I want to define the metering period for energy-metered devices using a configuration file.


actor Administrator
Administrator -> MainUI:run()
activate MainUI
MainUI -->> FileInputUtils: fileInputUtils = new FileInputUtils()
activate FileInputUtils

alt try
MainUI -> FileInputUtils: validGridMeteringPeriod()

ref over FileInputUtils
grid metering period
validation
end ref

alt valid configuration value
FileInputUtils --> MainUI: true
MainUI -> FileInputUtils: int deviceMeteringPeriod = this.mGridMeteringPeriod()

else invalid configuration value
FileInputUtils --> MainUI: false
deactivate FileInputUtils
MainUI -> Administrator: Error message
end


else catch Exceptions
MainUI -> Administrator: Error message

deactivate MainUI


end
@enduml