@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand
skinparam actor {
  BorderColor indianred
  }
skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}
skinparam roundcorner 10
skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}
title US147 \n As an Administrator, I want to have a list of existing rooms attached to a house grid, so that I can attach/detach rooms from it.  \n - Success Case -
autonumber
actor Administrator
Administrator -> ":EnergyGridSettingsUI": runUS147(house)
activate ":EnergyGridSettingsUI"
ref over ":EnergyGridSettingsUI"
Get Room by list
end ref
ref over ":EnergyGridSettingsUI"
Get Energy Grid by list
end ref
":EnergyGridSettingsUI" -> ":EnergyGridSettingsUI": updateGridUS147(energyGrid,room,house)
":EnergyGridSettingsUI" -> ":EnergyGridSettingsController": addRoomToGrid(grid, room, house)
activate ":EnergyGridSettingsController"
":EnergyGridSettingsController" -> ":EnergyGrid" : addRoom(room)
activate ":EnergyGrid"
":EnergyGrid" --> ":EnergyGridSettingsController" : return true
deactivate ":EnergyGrid"
":EnergyGridSettingsController" --> ":EnergyGridSettingsUI" : return true
deactivate ":EnergyGridSettingsController"
":EnergyGridSettingsUI" --> Administrator : show successful message
deactivate ":EnergyGridSettingsUI"
@enduml