@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

title GetInputFileLocation
actor Administrator
ReaderController -> InputUtils: getInputFileLocation()
activate InputUtils
create ":Scanner"
InputUtils -> ":Scanner": scanner = new Scanner()
activate ":Scanner"
":Scanner" -> Administrator: ask for file location
InputUtils -> ":Scanner": scanner.next()
deactivate ":Scanner"
Administrator -> InputUtils: file path

InputUtils -> InputUtils: pathIsValid(filePath)
InputUtils -> ReaderController: file path
deactivate InputUtils

@enduml