@startuml

title US70 \n REF: Get Device Types From Configuration File
autonumber



-> ":DeviceTypeConfig": getDeviceTypeConfig()
activate ":DeviceTypeConfig"
":DeviceTypeConfig" -> ":Properties": Properties props = new Properties()
activate ":Properties"
":DeviceTypeConfig" -> ":DeviceTypeConfig": FileInputStream input = new FileInputStream("resources/devices.properties")

":DeviceTypeConfig" -> ":Properties": props.load(input)

":DeviceTypeConfig" -> ":Properties": String deviceTypes = props.getProperty("allDeviceTypes")

":DeviceTypeConfig" -> ":DeviceTypeConfig": split deviceTypes to Array of keys

loop for each device key

":DeviceTypeConfig" -> ":Properties": String value = props.getProperty(key)
":DeviceTypeConfig" -> ":DeviceTypeConfig": deviceTypeConfig.add(value)
end
deactivate ":Properties"

<-- ":DeviceTypeConfig": return deviceTypeConfig

deactivate ":DeviceTypeConfig"

@enduml