@startuml

title US70 \n I want to configure the available device types for each instance of the system (i.e. each house) using a configuration file

autonumber

actor Admin

Admin -> MainUI: start program
activate MainUI

MainUI -> ":DeviceTypeConfig": getDeviceTypeConfig()
activate ":DeviceTypeConfig"
ref over ":DeviceTypeConfig"
Get Device Types
from Configuration File
end ref

":DeviceTypeConfig" --> MainUI: return deviceTypeConfig
deactivate ":DeviceTypeConfig"

MainUI -> ":House": House h = new House(deviceTypeConfig)
activate ":House"

":House" -> ":House": buildDeviceTypeList(deviceTypeConfig)

loop for each DT path in deviceTypeConfig
":House" -> "<<DeviceType>>": DeviceType dt = new DeviceType(String)
activate "<<DeviceType>>"
deactivate "<<DeviceType>>"

":House" -> ":House": mDeviceTypeList.add(dt)
end
deactivate ":House"

MainUI -> Admin: show option menu

deactivate MainUI


@enduml