@startuml
actor User
autonumber
User -> MainUI: Get Current Temperature on House Area
MainUI -> HouseMonitoringUI: Get Current Temperature on House Area
HouseMonitoringUI --> User: Request Geographic Area Name or Index from List
User -> MainUI: insert data (Geographic Area name) or Select GA
MainUI -> HouseMonitoringUI: select Geographic Area by name or from list
HouseMonitoringUI ->HouseMonitoringController: check if name/index is contained in list
HouseMonitoringController -> GeographicAreaList: check if name/index is contained in list
GeographicAreaList -> GeographicArea: match by name or by index
GeographicArea -> GeographicArea: validate data
GeographicArea --> HouseMonitoringUI: return Geographic Area
HouseMonitoringUI -> HouseMonitoringUI: set mGeoArea
HouseMonitoringUI --> User: Request House Name or Index from List
User -> MainUI: insert data (House name) or Select House
MainUI -> HouseMonitoringUI: select House by name or from list
HouseMonitoringUI -> HouseMonitoringController: check if name/index is contained in list
HouseMonitoringController -> HouseList: check if name/index is contained in list
HouseList -> House: match by name or by index
House -> House: validate data
House --> HouseMonitoringUI: return House
HouseMonitoringUI -> HouseMonitoringUI: set mHouse
HouseMonitoringUI -> HouseMonitoringController: getCurrentTemperatureInTheHouseArea
HouseMonitoringController->Sensor: getSensorWithTheMinimumDistanceToHouse
Sensor->ReadingList: getReadingList
ReadingList->Reading:getMostRecentValueOfReading
Reading-->HouseMonitoringUI: return Current Temperature In the House Area
HouseMonitoringUI -> HouseMonitoringUI: Build result string
HouseMonitoringUI -->User: Display result string

@enduml