@startuml
title US160 - List all devices on an Energy Grid ordered by type
actor PowerUser
PowerUser -> MainUI: run160(house)
activate MainUI
MainUI -> EnergyGridSettingsUI: run160(house)
activate EnergyGridSettingsUI
EnergyGridSettingsUI -> EnergyGridSettingsUI: validateHouse()
EnergyGridSettingsUI --> PowerUser: displayListOfGrids(house)
PowerUser -> MainUI: matchEnergyGridByIndex()
MainUI -> EnergyGridSettingsUI: matchEnergyGridByIndex()
EnergyGridSettingsUI -> EnergyGridSettingsController: matchEnergyGridByIndex()
activate EnergyGridSettingsController
EnergyGridSettingsController -> EnergyGridList: matchEnergyGridByIndex()
activate EnergyGridList
EnergyGridList --> EnergyGridSettingsController: return EnergyGrid
EnergyGridSettingsController -> EnergyGridSettingsController: validate EnergyGrid
EnergyGridSettingsController -> EnergyGridSettingsController: validate RoomList
EnergyGridSettingsController -> EnergyGridSettingsController: validate DeviceList
EnergyGridSettingsController -> EnergyGrid: buildListOfDevicesByType\n(EnergyGrid)
activate EnergyGrid
EnergyGrid --> PowerUser: Display ListOfDevices \nOrderedByType
deactivate MainUI
deactivate EnergyGridSettingsUI
deactivate EnergyGridSettingsController
deactivate EnergyGridList
deactivate EnergyGrid
@enduml