@startuml

title getInputPathJsonOrXML

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

actor Administrator

HouseConfigurationUI -> InputHelperUI: getInputPathJsonOrXML()
activate InputHelperUI
InputHelperUI -> Administrator: Ask user for input.
deactivate InputHelperUI

activate Administrator

Administrator -> InputHelperUI: Input path.
deactivate Administrator

activate InputHelperUI

alt if path is valid (ends with .json or .xml and exists)
 InputHelperUI-->HouseConfigurationUI: return true
else if path is invalid
loop
InputHelperUI -> Administrator: Ask user for input.
activate Administrator
deactivate InputHelperUI
end loop
end
@enduml