@startuml
title US015v2 \n REF JSON file.
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}
-> InputHelperUI: getInputPathJsonOrXML();
activate InputHelperUI
InputHelperUI -> ReaderController: readJSONFileAndAddGeoAreas(filePath)
activate ReaderController
ReaderController -> ReaderJSONGeographicAreas: readFile(filePath)
deactivate ReaderController
activate ReaderJSONGeographicAreas

ReaderJSONGeographicAreas->ReaderJSONGeographicAreas:getJSONArray("geographical_area")
ReaderJSONGeographicAreas --> ReaderController: return JSONArray
deactivate ReaderJSONGeographicAreas
activate ReaderController
loop
ReaderController->ReaderController:getJSONObject()
create "geoArea :GeographicArea"
ReaderController ->> "geoArea :GeographicArea": create
activate "geoArea :GeographicArea"
deactivate ReaderController
"geoArea :GeographicArea" --> ReaderController: return geoArea
deactivate "geoArea :GeographicArea"

activate ReaderController

ReaderController -> ReaderController: add to GeographicArea[]
loop
ReaderController->ReaderController:readAreaSensorsJSON(JSONArray)
create "sensor: Sensor"
ReaderController ->> "sensor: Sensor": create
activate "sensor: Sensor"
deactivate ReaderController

"sensor: Sensor" --> ReaderController: return sensor
deactivate "sensor: Sensor"

activate ReaderController
ReaderController -> "geoArea :GeographicArea": add(sensor)
end loop
end loop
loop
ReaderController -> GeographicAreaList: add(GeographicArea[])
deactivate ReaderController

activate GeographicAreaList

GeographicAreaList-->ReaderController: return true
deactivate GeographicAreaList

activate ReaderController
end loop
ReaderController --> InputHelperUI: return int
deactivate ReaderController
 <-- InputHelperUI: return int
 deactivate InputHelperUI

@enduml