@startuml
title US015v2 \n REF XML file.
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

-> InputHelperUI: getInputPathJsonOrXML();
activate InputHelperUI
InputHelperUI -> ReaderController: readFileXMLAndAddAreas(filePath)
activate ReaderController
ReaderController -> ReaderXML: readFile(filePath)
deactivate ReaderController
activate ReaderXML
ref over ReaderXML
XMLReadFile
end ref
ReaderXML --> ReaderController: return doc: Document
deactivate ReaderXML

activate ReaderController
ReaderController->ReaderController:NodeList = getElementsByTagName("geographical_area")
loop
ReaderController->ReaderController:readGeographicAreasXML(Node)
create "geoArea :GeographicArea"
ReaderController ->> "geoArea :GeographicArea": create
activate "geoArea :GeographicArea"
deactivate ReaderController

"geoArea :GeographicArea" --> ReaderController: return geoArea
deactivate "geoArea :GeographicArea"
activate ReaderController
loop
ReaderController->ReaderController:readSensorsXML(Node)
create "sensor: Sensor"
ReaderController ->> "sensor: Sensor": create
activate "sensor: Sensor"
deactivate ReaderController

"sensor: Sensor" --> ReaderController: return sensor
deactivate "sensor: Sensor"

activate ReaderController
ReaderController -> "geoArea :GeographicArea": add(sensor)
end loop
end loop

loop
ReaderController -> GeographicAreaList: add(geoArea)
deactivate ReaderController
activate GeographicAreaList

GeographicAreaList-->ReaderController: return true
deactivate GeographicAreaList

activate ReaderController

end loop
ReaderController --> InputHelperUI: return int
deactivate ReaderController
 <-- InputHelperUI: return int
 deactivate InputHelperUI
@enduml