@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

title US020 \n  I want to import geographical area sensor readings into the application from a CSV file. \n Data outside the valid sensor operation period shouldn’t be imported but registered in the application log.


actor Administrator
Administrator -> MainUI:run()
activate MainUI
MainUI -> HouseConfigurationUI: Import Geographic Area Sensor Readings from a CSV file.
activate HouseConfigurationUI
HouseConfigurationUI -> CSVReaderController: startAndPromptPath()
activate CSVReaderController
CSVReaderController -> HouseConfigurationUI: Request File Path
HouseConfigurationUI -> Administrator: Request File Path
Administrator --> HouseConfigurationUI: Insert File Path (.csv)
HouseConfigurationUI --> CSVReaderController: File Path (.csv)
CSVReaderController -> CSVReaderController: readAndSet(GeographicAreaList geographicAreaList, String path)
CSVReaderController -->> CSVReader: List<String[]> readCSV = readCSV(String csvFileLocation)
activate CSVReader
deactivate CSVReader
CSVReaderController -> CSVReaderController: getSensorData(GeographicAreaList geographicAreaList)
CSVReaderController -> CSVReaderController: parseAndLog(String[] readings, Logger logger, SensorList typeSensorList)

alt Try
CSVReaderController -> CSVReaderController: setCSVReadings(Sensor sensor, Date date, Double value)
else
CSVReaderController -> Log: Create new entry


deactivate HouseConfigurationUI


end
deactivate CSVReader
deactivate MainUI
deactivate HouseConfigurationUI
@enduml