@startuml

title File Path Prompt

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}



-> CSVReaderController: startAndPromptPath()
activate CSVReaderController
CSVReaderController -->> Scanner: input = new Scanner()

loop While

CSVReaderController -->> CSVReaderController: filePath != input.endsWith(".csv")
CSVReaderController -->> CSVReaderController: filePath != !new File(filePath).exists()


end



@enduml