@startuml

title Read CSV

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}




-> CSVReader: readCSV(String csvFileLocation)
activate CSVReader
CSVReader -->> ArrayList: List<String[]> listReads = new ArrayList<>();
CSVReader -->> String: String line = "";
CSVReader -->> String: String cvsSplit = ",";
alt try
CSVReader -->> FileReader: fileReader = new FileReader
CSVReader -->> BufferedReader: buffReader = new BufferedReader
loop  WHILE    line = buffReader.readLine()) != null
CSVReader -> CSVReader:readings = line.split(cvsSplit);
CSVReader -> CSVReader:listReads.add(readings);
end

else catch
CSVReader -> CSVReader: IOException

end
<- CSVReader: listReads
deactivate CSVReader
@enduml